replicaCount: 3

image:
  repository: mi-app-web
  tag: "latest"
  pullPolicy: Never        # Never porque la imagen es local en Minikube

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

app:
  message: "Hola desde Kubernetes!"
